services:
  - type: web
    name: chatbot-api
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=src uvicorn src.main:app --host 0.0.0.0 --port 8000"
    plan: free
